[package]
name = "TokenRegistry"
version = "0.0.2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "22fd977c77cdcf9a3285a7555a8b0eb65e97e899" }

[addresses]
AptosFramework = "0x1"
Std = "0x1"
TokenRegistry = "_"


