[package]
name = "TokenRegistry"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "bb3a847c6ae8967661826775cd026f6fdb2abf0c" }

[addresses]
TokenRegistry = "0x49c5e3ec5041062f02a352e4a2d03ce2bb820d94e8ca736b08a324f8dc634790"
AptosFramework = "0x1"
Std = "0x1"


